### ISSUE TITLE
404 sites

### ISSUE THREAD

**Issue by michaelachrisco** [basharovV/StumbleUponAwesome#1]
A couple of the sites are no longer working. For example:
https://sites.google.com/a/ddahl.org/rinruby-users/ is a 404.

**Comment by michaelachrisco** [comment]
Ah I see, the above was removed and the Firefox extension is not up to date. Thats fine, ill close this one out.

**Comment by basharovV** [comment]
Hi I've ran the script again and released version 1.2.0. Should take care of many 404s.
